### ISSUE TITLE
GH slow after [three-phase] radiance simulation

### ISSUE THREAD

**Issue by TheodoreGalanos** [ladybug-tools/honeybee-grasshopper#10]
Not sure if this is a bug or not but I thought I'd leave it here and see if anyone else noticed.

I have been experiencing major delays in GH after running 3-phase radiance simulations following the example file (with the post-processing workflow). I think this happened in other simulations as well. 

Memory utilisation is not that much (4gb, I have 32gb) and CPU utilisation is very low. But GH experiences major freezes (1-2 sec ones) and delays in the menus and actions inside (e.g. right click, space-bar menu , etc.).

Everything else is ok, simulation runs and post-processing is fine.

Has anyone else experienced this?

Kind regards,
Theodore.

**Comment by mostaphaRoudsari** [comment]
@TheodoreGalanos yes. I have experienced this too and I think it has to do with how grasshopper evaluates the viewport. Right click gets very slow however other stuff runs normal. I assume it has to do with the Grid object once it loads the results. Now that you can replicate this issue I will take a closer look.

**Comment by mostaphaRoudsari** [comment]
Just to confirm that this was because of how analysis grid was written. This has been addressed by breaking up results from the grid.
