### ISSUE TITLE
Error running Honeybee Plus example file #4, #8, #11

### ISSUE THREAD

**Issue by crossingchen** [ladybug-tools/honeybee-grasshopper#12]
I'm running the example file #11 for Honeybee Plus.
And get the following error from the runradiance module
`1. Solution exception:Failed to load the results form an empty file: c:\ladybug\test_room\gridbased_fivephase\result\scene..default.ill
Double check inputs and outputs and make sure everything is run correctly.`
![image](https://user-images.githubusercontent.com/5752865/30130021-b7cd424c-92fc-11e7-99fe-153712b43c4a.png)
The output from the runradiance module shows:

0. Found 6 opaque surfaces.
1. Found 0 fenestration surfaces.
2. Found 1 window-groups.
3.   [0] south_window, 1 state.
4. Writing recipe contents to: c:\ladybug\test_room\gridbased_fivephase
5. Copying clear.xml to c:\ladybug\test_room\gridbased_fivephase\scene\bsdf
6. One file from the radiance scene is added to the analysis.
7. Copying context.rad to c:\ladybug\test_room\gridbased_fivephase\scene\extra
8. Reusing SunMatrix: sunmtx_vis_724830_38.5_-121.5_0.0.mtx.
9. Unloading the current values from the analysis grids.
10. loading total and direct results for room_w_skylight AnalysisGrid from scene::default
c:\ladybug\test_room\gridbased_fivephase\result\scene..default.ill
c:\ladybug\test_room\gridbased_fivephase\result\sun..scene..default.ill
11. <empty>
12. Runtime error (Exception): Failed to load the results form an empty file: c:\ladybug\test_room\gridbased_fivephase\result\scene..default.ill
Double check inputs and outputs and make sure everything is run correctly.
13. Traceback:
  line 297, in setCoupledValuesFromFile, "C:\Users\xchen\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\honeybee\radiance\analysisgrid.py"
  line 336, in results, "C:\Users\xchen\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\honeybee\radiance\recipe\daylightcoeff\gridbased.py"
  line 65, in script

Here's what I got in the result folder
![image](https://user-images.githubusercontent.com/5752865/30131043-2741e9c2-9300-11e7-8b99-06ae3267e5e2.png)

The error also happens when I run example file #08_three_phase_I_gridbased and #04_annual_daylight_gridbased.

Can you please let me know what I can do to fix this issue? Thanks.

**Comment by crossingchen** [comment]
The version of radiance i used was 5.0.a.6. I also installed 5.0.12 version, which has the same error.

**Comment by mostaphaRoudsari** [comment]
@inkmug can you share the folder with me? You can remove the results folder.

Based on the screenshot you get the results for the direct sunlight with no issues but daylight coefficient calculations fail. I still think it's an issue with the Radiance version as it partially works. Can you try [the latest release](https://github.com/NREL/Radiance/releases/tag/5.1.0) of Radiance before sending the files.

**Comment by crossingchen** [comment]
I tested it with v5.1 and still have the issue.
Do you also need the tmp and sky folder? Those two are about 660MB. Should I just upload here? 
The rest stuffs are uploaded
[gridbased_threephase.zip](https://github.com/ladybug-tools/honeybee-grasshopper/files/1283435/gridbased_threephase.zip)

**Comment by mostaphaRoudsari** [comment]
@inkmug, sky folder will help! I don't need the temp folder though. Let me check the current files and I will let you know if the sky file is necessary.

**Comment by mostaphaRoudsari** [comment]
@inkmug, this folder is hard to debug. I need the original folder before running the analysis. You can either generate it by trying to write the files to a new folder or setting useDMtx input in recipe to False and write the files. Make sure run is set to False so it only writes the file to the folder.

Honeybee tries to re-use the results from the folder and because of that it doesn't remove the results from an older analysis. Since we're trying to debug I suggest to remove the whole folder before generating the new files.

**Comment by crossingchen** [comment]
@mostaphaRoudsari It's working now. So when I updated Radiance to v5.1.0 and reran the files, I didn't change the file names. I'm thinking as you said, the previous result is not removed from the folder so the error was still there. Now I rename the project and everything's fine now (all 3 files tested). Thanks for looking into this.

**Comment by mostaphaRoudsari** [comment]
@inkmug great! Thank you for the update!

**Comment by fposadas417** [comment]
@mostaphaRoudsari  Hi what version of Radiance should I be running? I get the exact same error as shown above but I am working off Radiance 5.1 as recommended with the HB+[04] installer.
