### ISSUE TITLE
HoneybeePlus_Radiance Parameters Image-based wrong input variable

### ISSUE THREAD

**Issue by Vyrwn** [ladybug-tools/honeybee-grasshopper#14]
the latest HoneybeePlus_Radiance Parameters Image-based that I downloaded has an issue with the radOptPar_ input. 

![image](https://user-images.githubusercontent.com/10517740/30765711-f2c1f624-9fe8-11e7-9bb9-9d3907c55055.png)

![image](https://user-images.githubusercontent.com/10517740/30765718-f8eb0d2e-9fe8-11e7-9995-f6fa2938fe50.png)

Its not a big issue, just wanted to let you know.

**Comment by Vyrwn** [comment]
obviously I meant -ab 6 :)

**Comment by mostaphaRoudsari** [comment]
Addressed via https://github.com/ladybug-tools/honeybee-grasshopper/commit/087c23980b1e491456a8412b16a105806a71bdd8
