### ISSUE TITLE
Add read results file for annual daylight sim

### ISSUE THREAD

**Issue by twanito** [ladybug-tools/honeybee-grasshopper#15]
I've been loving the addition of HoneyBee[+] for annual daylight simulation as it means I can output all results files to docker and run it on a vm. It's meant I can run large scale parametrics super cheap and quickly online but I'm having difficulties reading the outputs when back in grasshopper as the annual daylight metrics component only takes an analysisGrid produced within GH. Not really wanting to mess around with internal HB[+] code to get this to work as I fear I'll break something.

Here's the link to the docker image if interested [radhoneywhale](https://hub.docker.com/r/antoinedao/radhoneywhale/). I'm open to a better name if anyone thinks of one ;)

**Comment by mostaphaRoudsari** [comment]
Hi @twanito, I'm not sure why I didn't see this before! I even sent you, or someone who I thought is you, a note on twitter about radhoneywhale!

Anyways to answer this question, you can load the values with a code similar to these lines:

```python
# create and analysis grid from point file
analysisGird = AnalysisGrid.fromFile(points_file)  # once pep8 branch is merged it will be .from_file
# load the results
analysisGrid.setValuesFromFile(result_file, hoy, startLine=0, header=False, mode=0)  # once pep8 branch is merged it will be .set_values_from_file
```
Here is an example for [a grid-based recipe](https://github.com/ladybug-tools/honeybee/blob/8424e52e3775f22c42b8eea189d8ec86751ed314/honeybee/radiance/recipe/pointintime/gridbased.py#L260-L285).

Back to docker image I added the functionalities to honeybee to send requests and get the results in JSON format. You can use `AnalysisGrid.from_json` method to get the results back. Once I push it to the master branch I can upload an example.

**Comment by AntoineDao** [comment]
I’m seeing all of these messages a week late but this sounds great! I’ve been spying the apparition of json formats in Honeybee workflows and can’t wai to implement. Will be sure to try this when bringing results back into grasshopper to visualise (or sending to d3js once someone figures out hb grid + geometry to web formats :) )

**Comment by mostaphaRoudsari** [comment]
This is pretty old! I'm going to close this for now.

**Comment by AntoineDao** [comment]
Goodbye OG pollination collaboration issue !
