### ISSUE TITLE
Importing vs loading vs using modules

### ISSUE THREAD

**Issue by MingboPeng** [ladybug-tools/honeybee-grasshopper#17]
Hi Mostapha,

I have been having problems using "Rad Parameters". it is saying 'module' object has no attribute 'radiance'
![image](https://user-images.githubusercontent.com/9031066/34415394-7ef9bfae-ebbc-11e7-9646-6ff0748c4782.png)

**This only happens when I open the Rhino the first time, and it works after I restarted Rhino.**

I am guessing it might related to the order of how Rhino loads the modules in its scripts folder.

it is easy to fix, but curious what's happening behind this.

`import honeybee.radiance.recipe.parameters` TO `from honeybee.radiance.recipe import parameters`

![image](https://user-images.githubusercontent.com/9031066/34415502-0dcf56b2-ebbd-11e7-8980-b05289cb05d1.png)

**Comment by mostaphaRoudsari** [comment]
Addressed via https://github.com/ladybug-tools/honeybee-grasshopper/commit/087c23980b1e491456a8412b16a105806a71bdd8
