### ISSUE TITLE
HoneybeePlus_Radiance Parameters Grid-based giving error

### ISSUE THREAD

**Issue by bhandarinikhil** [ladybug-tools/honeybee-grasshopper#18]
Hello Mostapha,
Not sure if this is a bug or not but I thought I'd leave it here.
I am getting problem in HoneybeePlus_Radiance Parameters Grid-based, it is giving some kind of error like 1. Solution exception:'module' object has no attribute 'getRadianceParametersGridBased'. i don't know why it is coming like this, i attached a image file also.
Regards,
Nikhil
![untitled-1](https://user-images.githubusercontent.com/35499402/35002718-8b6c9ff0-fb10-11e7-801c-6ed8b51a4921.jpg)
.

**Comment by mostaphaRoudsari** [comment]
Hi @bhandarinikhil, Thank you for opening this issue. Is this change solve the problem in your case?
https://github.com/ladybug-tools/honeybee-grasshopper/issues/17

**Comment by bhandarinikhil** [comment]
Hello,
I tried #17 but still issue is same.
![capture](https://user-images.githubusercontent.com/35499402/35025318-c94c2052-fb6a-11e7-8018-0c5a99c06e9c.JPG)

**Comment by bhandarinikhil** [comment]
Hello Mostapha,
Change in 59th line worked for me,
Thank You.
![capture](https://user-images.githubusercontent.com/35499402/35179593-92a1b9a8-fdc3-11e7-9427-bc0668485ec8.JPG)

**Comment by DambronOlivier** [comment]
@bhandarinikhil  thanks for the solution.

Could you do a commit to update this?

**Comment by bhandarinikhil** [comment]
Hi @DambronOlivier , I don't know whether i can do this or not because i don't know much about coding, but yea defiantly  i will try to do this.

**Comment by mostaphaRoudsari** [comment]
Finally get a chance to address this. sorry for the delay!
https://github.com/ladybug-tools/honeybee-grasshopper/commit/06698aa6fd8f1b629bfc9bf1a39c1eccb464ffa6

**Comment by bhandarinikhil** [comment]
@mostaphaRoudsari thank you so much sir.
