### ISSUE TITLE
Point in Time grid based Error : 1. Solution exception:need more than 1 values to unpack

### ISSUE THREAD

**Issue by DambronOlivier** [ladybug-tools/honeybee-grasshopper#19]
Hi @mostaphaRoudsari ,

This is just to report a bug while testing the updated point-in-time grid-based and there was an error with the Climate-based Sky component as following:
![1](https://user-images.githubusercontent.com/21184323/40846820-94763964-65b2-11e8-93cf-254b0f77f8e7.PNG)

saying: 
1. Solution exception:need more than 1 values to unpack

**Comment by mostaphaRoudsari** [comment]
@DambronOlivier, thanks for reporting. It works fine on my side.  Can you open the component and re-run it so we can see the full error report.

**Comment by mostaphaRoudsari** [comment]
@DambronOlivier, I'm going to close this for now. Let me know if the issue happens again.
