### ISSUE TITLE
remove Annual Solar Exposure component

### ISSUE THREAD

**Issue by zati89** [ladybug-tools/honeybee-grasshopper#23]
It´s confusing to have both components in GH (Annual Solar and Annual Sunlight eposure), since their icons are identical, and the Solar exposure component is not working, just the Sunlight exposure component is working

**Comment by mostaphaRoudsari** [comment]
Thank you for reporting. I removed the UserObject: https://github.com/ladybug-tools/honeybee-grasshopper/commit/535099eba96a9a393a221ddc36fed51142b339d2
