### ISSUE TITLE
honey bee plus error

### ISSUE THREAD

**Issue by saharrostamzad** [ladybug-tools/honeybee-grasshopper#26]
Hello
I run annual sunlight exposure and get this error.
"Solution exception: Direct values are not available to calculate ASE.
In most of the cases this is because you are using a point in time recipe or the three phase recipe. You should use one of the daylight coefficient based recipes or the five phase recipe instead."
How can I fix that?
Thanks

**Comment by chriswmackey** [comment]
@saharrostamzad ,

Please post all "how to" qestions to [the forum](discourse.ladybug.tools) and only post things realted to new development and bug fixes to the GitHub.

As the error says, you probably didn't connect up the correct type of recipe component to the "Run Daylight Simulation" component.
