### ISSUE TITLE
Schedules or HOYS for materials/geometry as opposed to states

### ISSUE THREAD

**Issue by DambronOlivier** [ladybug-tools/honeybee-grasshopper#27]
hi @mostaphaRoudsari  and @sariths 

Could HB+ integrate schedules for materials as opposed to states? 
Something such as : if 1 use material A if 0 use material B or remove geometry.

Here is a situation that illustrates my concern:
A building with a glazed facade (tvis=0.25) and glazed roof (tvis=0.45).
![img_20181113_120717](https://user-images.githubusercontent.com/21184323/48412850-cb062900-e73d-11e8-8994-dc89183be283.jpg)

Further to thermal analysis, we issue the schedules from energyplus with the HOYS when shading needs to be down. The shading on the facade is 66% opaque (34% permeable) and the one of the roof is 80% opaque (20% permeable). Their respective schedules happen to be asynchronous.
For practical reasons I chose not to model explicitly the shading but to change the glazing Tvis to the equivalent one of the complexe[glass+shading].
![img_20181113_120725](https://user-images.githubusercontent.com/21184323/48413032-4d8ee880-e73e-11e8-8e76-0ff8b3254184.jpg)

In order to obtain an annual metric here I am currently breaking it down into 4 cases set with their respective HOYS, reload all of them and do a weighted average of a weighted average:
![img_20181113_120735](https://user-images.githubusercontent.com/21184323/48413504-d3f7fa00-e73f-11e8-9294-49e847b0e3b1.jpg)

**Comment by sariths** [comment]
Hi @DambronOlivier , can't you keep geometry same for each state and just the material in each case? Or are you already doing that? Each state is run as a separate simulation, so everything remaining the same the only thing that will be changing in successive simulations is the material type. That is how I'd do it in command line. @mostaphaRoudsari will have a proper HB[+]-centric answer to this query!

**Comment by DambronOlivier** [comment]
Hi  @sariths, thanks for your reply. Yes indeed the geometry stays the same and only the material changes and the hoys for each case.
I need to decompose each case so as to get the annual metric at the end by weighted average.

If I use states, I would need to run the same hoys for all ( which is heavier), and I will be able to see the annual metrics with a combination of the states. I remember that until today, when the state of a material is turned off it is replaced by a dark opaque material which wouldn't be correct in this case.

**Comment by DambronOlivier** [comment]
see [https://discourse.ladybug.tools/t/3-phase-method-window-states-with-energyplus-schedule/4637/3](https://discourse.ladybug.tools/t/3-phase-method-window-states-with-energyplus-schedule/4637/3)
