### ISSUE TITLE
Honeybee[+] Surface returning Goo geometry

### ISSUE THREAD

**Issue by sweco-bepedm** [ladybug-tools/honeybee-grasshopper#34]
Hello there guys,

First, let me thank you for the incredible development. It's hard to believe that such a tool is open source and free for everyone to work on!

I recently migrated from Honeybee Legacy to Honeybee [+] and I found what I think is a bug in the component Honeybee Surface. The geometry returned from the component cannot be read as geometry from Rhino, I get the error "Data conversion failed from Goo to geometry".
Now this might not be a bug as you could just convert the geometry into HB-readable code, but in the legacy version this does not happen, and the name Goo could be a typo.

![Goo printscree](https://user-images.githubusercontent.com/12100722/61110842-84153280-a488-11e9-9479-bd4ca9b3f34e.png)

Keep up the good work!

**Comment by sweco-bepedm** [comment]
@AntoineDao this is not an issue with flattening. I tested it and it is the same behavior.

@mostaphaRoudsari your fix solved the issue, thanks! Now that I know this trick I can create the converter myself. I find it very useful to do a last check of the geometry going in the recipe before running it.

**Comment by snoringpanda96** [comment]
![image](https://user-images.githubusercontent.com/94423594/141890291-6bd79a70-1498-4748-a744-a2097e4fd0d6.png)
Hi, thanks for the suggestion. I have tried creating the python script as suggested, but received the error '1. Solution exception:'HBSurface' object has no attribute '_isCeatedFromGeo'' in return. Would very much appreciate any form of help, thank you!

**Comment by mostaphaRoudsari** [comment]
Hi @snoringpanda96, we are not maintaining this Honeybee[+] anymore. You should try using honeybee-radiance instead. It comes with the new Ladybug Tools plugins also known as the LBT plugins.
