### ISSUE TITLE
Honeybee[+] Hourly Values returning integer

### ISSUE THREAD

**Issue by sweco-bepedm** [ladybug-tools/honeybee-grasshopper#35]
Hi guys,

I was testing around and running daylight factor simulations with HB[+] and i found out that using the Hourly Value to transform the analysis grid into hourly values, I am getting integers returned. For DA the results are certainly acceptable but less so for DLF values, there could be errors of 50% in low values like DLF = 1%! Is there another way to get these values correctly out?

![image](https://user-images.githubusercontent.com/12100722/61141745-89956b80-a4ce-11e9-90e2-292ce4a0eb7d.png)

**Comment by mostaphaRoudsari** [comment]
Hi @pmcmm, see here: https://discourse.ladybug.tools/t/daylight-factor-rounded-values/2619/2

**Comment by sweco-bepedm** [comment]
thanks for solving it again, @mostaphaRoudsari. Discourse seems more active than github. For these simple questions should I start posting on discourse instead then?

**Comment by mostaphaRoudsari** [comment]
Yes. Questions should be posted to the forum not on GitHub.
