### ISSUE TITLE
HoneybeePlus_Honeybee Surface running error

### ISSUE THREAD

**Issue by ymg2007** [ladybug-tools/honeybee-grasshopper#7]
I have download the honeybee_plus package. Then I drop the ghuser to grasshooper windows. But when I run the first example,grasshooper give me some error:   **Solution exception:"fromGeometries" method can only be used in [+] libraries.**
![image](https://user-images.githubusercontent.com/24608776/28995094-df86db9e-7a11-11e7-9198-34564150d519.png)

**Comment by mostaphaRoudsari** [comment]
Hi @ymg2007, see here: https://github.com/ladybug-tools/honeybee/issues/179#issuecomment-320679562

**Comment by mostaphaRoudsari** [comment]
@ymg2007 any updates on this?

**Comment by ymg2007** [comment]
@mostaphaRoudsari I am sorry for reply lately. My question has been resolved. Thank you!!!
