### ISSUE TITLE
Error after installation 

### ISSUE THREAD

**Issue by TheodoreGalanos** [ladybug-tools/honeybee-grasshopper#8]
This is a continuation of https://github.com/ladybug-tools/honeybee/issues/179

I used the install file provided with HB+ but I am still getting the generic error "Solution exception:len() of unsized object" I mentioned before.

Testing the component gives out a series of errors in the python files of the installation:

> Runtime error (TypeErrorException): len() of unsized object
Traceback:
  line 96, in join, "C:\Program Files\Rhinoceros 5 (64-bit)\Plug-ins\IronPython\Lib\ntpath.py"
  line 103, in openStudioPath, "C:\Users\Athena\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\honeybee\config.py"
  line 250, in <module>, "C:\Users\Athena\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\honeybee\config.py"
  line 4, in <module>, "C:\Users\Athena\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\honeybee\futil.py"
  line 5, in <module>, "C:\Users\Athena\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\honeybee\radiance\radfile.py"
  line 10, in <module>, "C:\Users\Athena\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\honeybee\surfaceproperties.py"
  line 4, in <module>, "C:\Users\Athena\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\honeybee\_hbanalysissurface.py"
  line 1, in <module>, "C:\Users\Athena\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\honeybee\hbsurface.py"
  line 50, in script
  line 53, in __init__, "C:\Users\Athena\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\honeybee\config.py"

Not sure if it's something related to my installation/PC setup.

Kind regards,
Theodore.

**Comment by mostaphaRoudsari** [comment]
@TheodoreGalanos do you have OpenStudio installed on your machine? I'm adding an extra check to avoid this issue.

**Comment by mostaphaRoudsari** [comment]
@TheodoreGalanos can you update the installation using the update component, restart Rhino and Grasshopper and try again? The issue should hopefully be solved.

**Comment by Omidmr** [comment]
Hi @mostaphaRoudsari, 

After Update, the error message:

> Runtime error (MissingMemberException): 'Folders' object has no attribute '_configFile'
Traceback:
  line 235, in loadFromFile, "C:\Users\OMD\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\honeybee\config.py"
  line 50, in __init__, "C:\Users\OMD\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\honeybee\config.py"
  line 251, in <module>, "C:\Users\OMD\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\honeybee\config.py"
  line 4, in <module>, "C:\Users\OMD\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\honeybee\futil.py"
  line 5, in <module>, "C:\Users\OMD\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\honeybee\radiance\radfile.py"
  line 10, in <module>, "C:\Users\OMD\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\honeybee\surfaceproperties.py"
  line 4, in <module>, "C:\Users\OMD\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\honeybee\_hbanalysissurface.py"
  line 1, in <module>, "C:\Users\OMD\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\honeybee\hbsurface.py"
  line 50, in script

-Omid

**Comment by TheodoreGalanos** [comment]
Hi @mostaphaRoudsari thanks. I won't have access to the work pc till monday but I'll give a clean install in my home pc now and let you know.

Kind regards,
Theodore.

**Comment by mostaphaRoudsari** [comment]
@Omidmr thanks for testing the installation. [This](https://github.com/ladybug-tools/honeybee/commit/01ae9732f4567080e51a3326822ae9d0737ff3de) should solve the bug that you mentioned. Can you try to update again?

**Comment by Omidmr** [comment]
Nice!, It solved, @mostaphaRoudsari. (replace manually with a new config.py file).
I was Update in 2 or more times by using the update component, restart Rhino and Grasshopper(**Without any change in error message**).
I checked The config.py in Honeybee folder, after updating, that won't update.
![ssss](https://user-images.githubusercontent.com/11173265/29242655-fc490934-7fa5-11e7-87de-17e5d78167f7.png)

Thanks.
-Omid

**Comment by TheodoreGalanos** [comment]
Hi @mostaphaRoudsari Updating worked! Thanks!

**Comment by mostaphaRoudsari** [comment]
Great! You can download the example files from this folder: https://github.com/ladybug-tools/honeybee-grasshopper/tree/master/plugin/grasshopper/sampleFiles

I'm updating them right now. I will be offline for a couple of days but feel free to open an issue if you found any issues.

**Comment by theo-armour** [comment]
Yay! Mostapha is going to take a little holiday

My apologies for being off-topic. ;-)
